apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "he-client.fullname" . }}
  labels:
    {{- include "he-client.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "he-client.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "he-client.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: "{{ .Chart.Name }}-go"
          image: "{{ .Values.image.goRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: goPort
              containerPort: {{ .Values.service.goPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: EXTERNAL_URL
              value: ""
            - name: HTTP_PORT
              value: "{{ .service.goPort }}"
            - name: AGGREGATION_SERVICE_URL
              value: {{ .service.aggregationService }}
            - name: PYTHON_HOST
              value: "{{ .he-client.fullname }}"
            - name: PYTHON_PORT
              value: "{{ .service.pythonPort }}"
            - name: PYTHON_API_PATH
              value: "/api"
        - name: "{{.Chart.Name }}-python"
          image: "{{ .Values.image.pythonRepository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pythonPort
              containerPort: {{ .Values.service.pythonPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.pythonLivenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.pythonReadinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PYTHON_HOST
              value: "{{ .he-client.fullname }}"
            - name: PYTHON_PORT
              value: "{{ .service.pythonPort }}"
            - name: PYTHON_API_PATH
              value: "/api"
            - name: ML_MODEL_NAME
              value: "{{ .service.mlModelName }}"
            - name: ML_MODEL_VERSION
              value: "{{ .service.mlModelVersion }}"
            - name: ML_MODEL_PATH
              value: "{{ .service.mlModelPath }}"
            - name: ML_EPOCHS
              value: "{{ .service.mlEpochs }}"
            - name: ML_LOG_INTERVAL
              value: "{{ .service.mlLogInterval }}"
            - name: DATA_SPLIT_NUM_PARTIES
              value: "{{ .service.numClients }}"
            - name: DATA_SPLIT_PARTY
              value: "{{ .service.dataSplitParty }}"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
