apiVersion: v1
kind: Service
metadata:
  name: {{ include "heclient.fullname" . }}
  labels:
    {{- include "heclient.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.goPort }}
      targetPort: goPort
      protocol: TCP
      name: goPort
    - port: {{ .Values.service.pythonPort }}
      targetPort: pythonPort
      protocol: TCP
      name: pythonPort
  selector:
    {{- include "heclient.selectorLabels" . | nindent 4 }}
