apiVersion: v1
kind: Pod
metadata:
  labels:
    app: he-aggregation-server
  name: he-aggregation-server
spec:
  containers:
  - name: aggregation-server
    image: ghcr.io/timonsachweh/ds-multi-party-homomorphic-encryption/aggregation-server:main
    env:
    - name: HTTP_PORT
      value: "8080"
    - name: MIN_CLIENTS_NEEDED
      value: "2"
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
    ports:
    - containerPort: 8080
      name: he-agg-endpoint
---
apiVersion: v1
kind: Service
metadata:
  name: he-aggregation-server
spec:
  selector:
    app.kubernetes.io/name: he-aggregation-server
  ports:
  - name: http-service-endpoint
    protocol: TCP
    port: 8080
    targetPort: he-agg-endpoint
