apiVersion: v1
kind: Pod
metadata:
  labels:
    app: he-aggregation-server
  name: he-aggregation-server
spec:
  containers:
  - name: aggregation-server
    image: he-aggregation-server:latest
    env:
    - name: HTTP_PORT
      value: 8080
    - name: CLIENT_SERVICE_URLS
      value: http://he-client-1:8081
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
    ports:
    - containerPort: 8080
      hostPort: 8080