apiVersion: v1
kind: Pod
metadata:
  labels:
    app: he-client-1
  name: he-client-1
spec:
  containers:
  - name: he-client-1
    image: he-client:latest
    env:
    - name: HTTP_PORT
      value: 8081
    - name: AGGREGATION_SERVICE_URL
      value: http://he-aggregation-server:8080/v1
    - name: PYTHON_HOST
      value: http://localhost
    - name: PYTHON_PORT
      value: 5001
    livenessProbe:
      httpGet:
        path: /health
        port: 8081
    ports:
    - containerPort: 8081
      hostPort: 8081
  - name: python-client-1
    image: he-python-client:latest
    env:
    - name: PYTHON_PORT
      value: 5001
    livenessProbe:
      httpGet:
        path: /health
        port: 5001
    ports:
    - containerPort: 5001