apiVersion: v1
kind: Pod
metadata:
  labels:
    app: he-client-${CLIENT_ID}
  name: he-client-${CLIENT_ID}
spec:
  containers:
  - name: he-client-${CLIENT_ID}
    image: ghcr.io/timonsachweh/ds-multi-party-homomorphic-encryption/he-client:main
    env:
    - name: HTTP_PORT
      value: "8080"
    - name: AGGREGATION_SERVICE_URL
      value: http://he-aggregation-server:8080/v1
    - name: PYTHON_HOST
      value: http://he-client-${CLIENT_ID}
    - name: PYTHON_PORT
      value: "5001"
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
    ports:
    - containerPort: 8080
      name: go-client
  - name: python-client-${CLIENT_ID}
    image: ghcr.io/timonsachweh/ds-multi-party-homomorphic-encryption/python-client:main
    env:
    - name: PYTHON_PORT
      value: "5001"
    livenessProbe:
      httpGet:
        path: /health
        port: 5001
    ports:
    - containerPort: 5001
      name: python-port
---
apiVersion: v1
kind: Service
metadata:
  name: he-client-${CLIENT_ID}
spec:
  selector:
    app.kubernetes.io/name: he-client-${CLIENT_ID}
  ports:
  - name: go-service
    protocol: TCP
    port: 8080
    targetPort: go-client
  - name: python-service
    protocol: TCP
    port: 5001
    targetPort: python-port
