services:
  aggregation-server:
    image: aggregation-server:latest
    build:
      context: ../aggregation-server/
      dockerfile: Dockerfile
    environment:
      HTTP_PORT: 8080
      DB_URL: mongodb://mongo:27017
      DB_USERNAME: agdsmphe
      DB_PASSWORD: aöseotiwqr534r5wefsdfvjsb212
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      retries: 5
      start_period: 2s
      timeout: 10s

  he-client-1:
    image: he-client:latest
    build:
      context: ../he-client/
      dockerfile: Dockerfile
    environment:
      HTTP_PORT: 8080
      AGGREGATION_SERVICE_URL: http://aggregation-server:8080/v1
      PYTHON_HOST: http://python-client-1
      PYTHON_PORT: 8080
    depends_on:
      - aggregation-server
      - python-client-1
    ports:
      - "8081:8080"
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      retries: 5
      start_period: 2s
      timeout: 10s

  python-client-1:
    image: python-client-1:latest
    build:
      context: ../python-client/
      dockerfile: Dockerfile.mac-gpu
    environment:
      PYTHON_PORT: 8080
    depends_on:
      - aggregation-server
    healthcheck:
      test: curl --fail http://localhost:8080/health || exit 1
      interval: 5s
      retries: 5
      start_period: 2s
      timeout: 10s
    
  